#### GENERAL INSTRUCTIONS: Place your code in each cell to perform the required calculations.  Ctrl-Enter will execute all lines of code in that cell. Once you are satisfied with your answer (you may work through it as much as you'd like), click on the "Submit Assignment" button in the upper right corner and your assignment will be graded.

#### For Parts A through D, you will use the following vectors, `x`, `y`, and `z`.  Using the code below, these vectors will be generated automatically for you in random order (such that every learner has a unique set of vectors).  When the grader runs your file, new random vectors will be chosen, so it's important that you write your answer in terms of `x`, `y`, and `z` and not simple numerical values.

In [1]:
# DO NOT CHANGE ANYTHING IN THIS CELL!

# Generate random vectors x, y, and z
v <- sample.int(12)
x <- v[1:4]
y <- v[5:8]
z <- v[9:12]
cat("x =",x,"\n")
cat("y =",y,"\n")
cat("z =",z,"\n")

# Be sure to run this block (Ctrl-Enter) before beginning parts A through D!  If you re-run this block, then the
# values of x, y, and z will change, so be sure to re-run subsequent cells in that case.

x = 3 7 6 4 
y = 8 11 2 5 
z = 9 12 1 10 


#### Part A
How would you extract the 3rd element of vector `y` and store it in the variable `PartA`?

In [2]:
# your code here


PartA <- y[3]
print(PartA)

[1] 2


#### Part B
How would you create a new vector that represents only the 1st and 3rd elements of vector `z`?  Store your answer in the variable `PartB`.

In [3]:
# your code here


PartB <- z[c(1, 3)]
print(PartB)

[1] 9 1


#### Part C 
Given the vectors `x`, `y`, and `z`, how would you write code in R to create the following matrix, `C`?  Store your answer in the variable `PartC` and make sure that your answer is in terms of the vectors `x`, `y`, and `z`.

$$x=[x_1,x_2,x_3,x_4]$$
$$y=[y_1,y_2,y_3,y_4]$$
$$z=[z_1,z_2,z_3,z_4]$$

$$C=\begin{bmatrix} x_1 & x_4 & y_3 & z_2 \\ x_2 & y_1 & y_4 & z_3 \\ x_3 & y_2 & z_1 & z_4 \end{bmatrix}$$

In [4]:
# your code here


PartC <- matrix(c(x[1], x[4], y[3], z[2], 
                  x[2], y[1], y[4], z[3], 
                  x[3], y[2], z[1], z[4]), 
                nrow = 3, byrow = TRUE)
print(PartC)

     [,1] [,2] [,3] [,4]
[1,]    3    4    2   12
[2,]    7    8    5    1
[3,]    6   11    9   10


#### Part D
Given the vectors `x`, `y`, and `z` below, how would you write code in R to create the following matrix, `D`?  Store your answer in the variable `PartD` and make sure that your answer is in terms of the vectors `x`, `y`, and `z`.

$$x=[x_1,x_2,x_3,x_4]$$
$$y=[y_1,y_2,y_3,y_4]$$
$$z=[z_1,z_2,z_3,z_4]$$

$$D=\begin{bmatrix} x_1 & x_2 & x_3 & x_4 \\ y_1 & y_2 & y_3 & y_4 \\ z_1 & z_2 & z_3 & z_4 \end{bmatrix}$$

In [5]:
# your code here


PartD <- matrix(c(x, y, z), nrow = 3, byrow = TRUE)
print(PartD)

     [,1] [,2] [,3] [,4]
[1,]    3    7    6    4
[2,]    8   11    2    5
[3,]    9   12    1   10


#### For Parts E and F, you will use the following matrix, `E`.  Using the code below, this matrix will be generated automatically for you in a random configuration (such that every learner has a unique matrix).   When the grader runs your file, a new random matrix will be chosen, so it's important that you write your answer in terms of matrix `E` and not simple numerical values.

In [6]:
# DO NOT CHANGE ANYTHING IN THIS CELL!

# Generate random matrix E
E <- matrix(sample.int(16),nrow=4,ncol=4)
print(E)

# Be sure to run this block (Ctrl-Enter) before beginning parts E and F!  If you re-run this block, then the
# values in matrix E will change, so be sure to re-run subsequent cells in that case.

     [,1] [,2] [,3] [,4]
[1,]    6   15   14   12
[2,]    2    1    8    4
[3,]   16    5    9   10
[4,]   13    3   11    7


#### Part E
How would you extract only the 3rd column of matrix `E`?  Store your resulting vector in the variable `PartE`.

In [7]:
# your code here


PartE <- E[, 3]
print(PartE)

[1] 14  8  9 11


#### Part F
How would you extract the elements of the 2nd, 3rd, and 4th rows but only columns 1 and 3 of matrix `E`?  Store your resulting matrix in the variable `PartF`.

In [8]:
# your code here


PartF <- E[c(2, 3, 4), c(1, 3)]
print(PartF)

     [,1] [,2]
[1,]    2    8
[2,]   16    9
[3,]   13   11


#### Part G
Data for the mass of burritos from four different restaurants are available in the file "Burritos.xlsx" (same directory as this file, so the file path to import is simply the file name).  You might want to copy/paste that file name in your solution so you don't misspell it.

First, import the data using the **read_excel** function (be sure to load the proper library!).  Next, extract only the 5 values from the **Qdoba1** column and store the data in a new vector (NOT a tibble!) named `PartG`.

In [9]:
# your code here


# Load the necessary library
library(readxl)

# Read the data from Burritos.xlsx
burrito_data <- read_excel("Burritos.xlsx")

# Extract only the 5 values from the "Qdoba1" column and convert to a vector
PartG <- as.vector(burrito_data$Qdoba1[1:5])

print(PartG)

[1] 693.0 669.8 693.1 715.7 691.8
